const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const ts = require('typescript')
const vm = require('node:vm')
const api = {}
const source = fs.readFileSync(path.join(__dirname, '../src/utils/operationsWork.ts'), 'utf8')
vm.runInNewContext(ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText, { exports: api })
const todo = (signal, count = 1) => ({ key: 'fulfillment_review', count, unread_count: count, signals: [signal] })
assert.equal(api.unseenWork([todo('order:1:revision:1')], new Set()).length, 1)
assert.equal(api.unseenWork([todo('order:1:revision:1')], new Set(['order:1:revision:1'])).length, 0)
// Same count, different order or a new anomaly revision must still notify.
assert.equal(api.unseenWork([todo('order:2:revision:1')], new Set(['order:1:revision:1'])).length, 1)
assert.equal(api.unseenWork([todo('order:1:revision:2')], new Set(['order:1:revision:1'])).length, 1)
assert.equal(api.unseenWork([todo('order:1:revision:1', 0)], new Set()).length, 0)
assert.equal(api.waitLabel(null), '暂无待办')
assert.equal(api.waitLabel('2026-10-07T00:00:00Z', Date.parse('2026-10-07T02:00:00Z')), '2 小时')
assert.equal(api.waitLabel('invalid'), '待处理')
console.log('PASS work notification dedupe, same-count replacement, new revision and waiting time')
