<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { adminApi } from '../services/api'
import type { ProviderOrderingSetting } from '../types'
const loading=ref(false),saving=ref(false),updatedAt=ref('')
const form=reactive({location_report_interval_seconds:300,location_timeout_minutes:30,max_location_accuracy_m:200,acceptance_timeout_minutes:30})
async function load(){loading.value=true;try{const data=await adminApi.providerOrderingSetting();Object.assign(form,data);updatedAt.value=data.updated_at}catch(e){ElMessage.error(e instanceof Error?e.message:'接单规则加载失败')}finally{loading.value=false}}
async function save(){saving.value=true;try{const data=await adminApi.updateProviderOrderingSetting(form as Partial<ProviderOrderingSetting>);Object.assign(form,data);updatedAt.value=data.updated_at;ElMessage.success('接单规则已保存并写入审计日志')}catch(e){ElMessage.error(e instanceof Error?e.message:'保存失败')}finally{saving.value=false}}
onMounted(load)
</script>
<template><div class="page rules-page" v-loading="loading"><header class="page-heading"><div><h1>接单规则</h1><p>配置达人定位有效性与支付后接单时限，修改后对后续业务判断生效</p></div><el-button type="primary" :loading="saving" @click="save">保存规则</el-button></header><section class="rule-panel"><h2>定位与在线状态</h2><div class="rule-grid"><label><span>位置上报间隔</span><el-input-number v-model="form.location_report_interval_seconds" :min="60" :max="900" :step="60"/><small>秒，建议 300 秒</small></label><label><span>定位失效时间</span><el-input-number v-model="form.location_timeout_minutes" :min="10" :max="120" :step="5"/><small>分钟，超时后达人显示离线</small></label><label><span>最大定位误差</span><el-input-number v-model="form.max_location_accuracy_m" :min="50" :max="200" :step="10"/><small>米，超过后位置判定无效</small></label></div><h2>订单响应</h2><div class="rule-grid"><label><span>支付后接单时限</span><el-input-number v-model="form.acceptance_timeout_minutes" :min="5" :max="120" :step="5"/><small>分钟，超时后不可继续接单</small></label></div><footer>最后更新：{{ updatedAt ? new Date(updatedAt).toLocaleString('zh-CN',{hour12:false}) : '尚未保存' }}</footer></section></div></template>
<style scoped>.rules-page{min-height:calc(100vh - 76px)}.rule-panel{padding:26px;border:1px solid var(--line);border-radius:8px;background:#fff}.rule-panel h2{margin:0 0 18px;font-size:16px}.rule-panel h2:not(:first-child){margin-top:32px;padding-top:25px;border-top:1px solid #edf0f2}.rule-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.rule-grid label{display:flex;flex-direction:column;gap:10px;padding:18px;border:1px solid #e5eaed;border-radius:8px;background:#fbfcfc}.rule-grid label>span{font-size:13px;font-weight:650}.rule-grid small,.rule-panel footer{color:var(--muted);font-size:12px}.rule-panel footer{margin-top:28px;text-align:right}@media(max-width:1100px){.rule-grid{grid-template-columns:1fr 1fr}}</style>
